server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cars
        driverClassName: org.postgresql.Driver
        username: postgres
        password: student
    jpa:
        hibernate:
            ddl-auto: update