server:
    port: 8080

spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:./data/fileDB
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update